#!/usr/bin/env python3

__version__ = '0.3.2'
__modified__ = ("2021", "02", "01")
__author__ = "Hugo 'iRyukizo' MOREAU"
__maintainer__ = "Hugo 'iRyukizo' MOREAU"
__status__ = "Production"

from checklines import main

if __name__ == "__main__":
    exit(main.checklines_main())
