#!/usr/bin/env python3

__version__ = '0.2.9'
__modified__ = ("2020", "12", "25")
__author__ = "Hugo 'iRyukizo' MOREAU"
__maintainer__ = "Hugo 'iRyukizo' MOREAU"
__status__ = "Production"

from checklines import main

if __name__ == "__main__":
    exit(main.checklines_main())
