repos:
- repo: local
  hooks:
  - id: clang-format
    name: coding style
    entry: clang-format --Werror --dry-run
    language: system
    files: \.(c|h)$
  - id: check_lines
    name: Check lines
    entry: check_lines
    args: [-l 25]
    language: system
    files: \.(c)$
  - id: check_lines -a
    name: Check exported and static functions
    entry: check_lines
    args: [-a]
    language: system
    files: \.(c)$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
  - id: forbid-binary
